#!/usr/bin/python3
"""Module that factorize as many numbers as possible
 into a product of two smaller numbers."""
from sys import argv


def factorize(number):
    """"print a simple descomposition of an integer > 1"""
    i = 2

    if number < 2:
        return
    print()
    print(number, "<- number-bef")
    while number % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number, number / i, i))
    print(number, "<- number-aft")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number = int(line.split('\n')[0])
            factorize(number)
            line = file.readline()
except:
    pass
